tap 'argon/mas'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'codekitchen/dinghy'
tap 'homebrew/boneyard'
tap 'homebrew/brewdler'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'rcmdnk/file'
tap 'tldr-pages/tldr'
cask 'java'
cask 'xquartz'
brew 'autoconf'
brew 'autossh'
brew 'awscli'
brew 'gettext'
brew 'openssl'
brew 'axel'
brew 'boost'
brew 'bsdmake'
brew 'cctools'
brew 'cmake'
brew 'colordiff'
brew 'curl'
brew 'diff-so-fancy'
brew 'direnv'
brew 'dnsmasq'
brew 'git'
brew 'docker'
brew 'docker-machine'
brew 'libyaml'
brew 'docker-compose'
brew 'icu4c'
brew 'dwdiff'
brew 'elasticsearch'
brew 'exiftool'
brew 'lame'
brew 'x264'
brew 'xvid'
brew 'ffmpeg'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'fortune'
brew 'jpeg'
brew 'libtiff'
brew 'webp'
brew 'gd'
brew 'gdbm'
brew 'ghi'
brew 'little-cms2'
brew 'ghostscript'
brew 'ghq'
brew 'gibo'
brew 'gnu-getopt'
brew 'git-now'
brew 'git-secrets'
brew 'go'
brew 'libtool'
brew 'graphviz'
brew 'heroku'
brew 'hub'
brew 'xz'
brew 'imagemagick'
brew 'jbig2dec'
brew 'jo'
brew 'oniguruma'
brew 'jq'
brew 'libevent'
brew 'libffi'
brew 'libvo-aacenc'
brew 'libzip'
brew 'mackup'
brew 'mecab'
brew 'mecab-ipadic'
brew 'memcached', restart_service: true
brew 'mysql@5.6'
brew 'openssl@1.1'
brew 'pcre'
brew 'nginx'
brew 'nodebrew'
brew 'packer'
brew 'parallel'
brew 'peco'
brew 'pkg-config'
brew 'readline'
brew 'postgresql', restart_service: true
brew 'proctools'
brew 'pstree'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'q'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-binstubs'
brew 'reattach-to-user-namespace'
brew 'redis', restart_service: true
brew 'rmtrash'
brew 'shellcheck'
brew 'source-highlight'
brew 'spark'
brew 'sshrc'
brew 'terminal-notifier'
brew 'terraform'
brew 'the_silver_searcher'
brew 'tig'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'youtube-dl'
brew 'z'
brew 'zsh'
brew 'zsh-completions'
brew 'argon/mas/mas'
brew 'homebrew/boneyard/unfs3'
brew 'codekitchen/dinghy/dinghy'
brew 'homebrew/dupes/apple-gcc42'
brew 'tldr-pages/tldr/tldr'
cask '1password'
cask 'adobe-creative-cloud'
cask 'appcleaner'
cask 'atom'
cask 'bartender'
cask 'blisk'
cask 'caffeine'
cask 'chefdk'
cask 'clipy'
cask 'cmd-eikana'
cask 'cyberduck'
cask 'dash'
cask 'disk-inventory-x'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'franz'
cask 'google-chrome'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'google-photos-backup'
cask 'gyazo'
cask 'handbrake'
cask 'hosts'
cask 'imageoptim'
cask 'istat-menus'
cask 'iterm2-beta'
cask 'jasper'
cask 'licecap'
cask 'maczip4win'
cask 'medis'
cask 'microsoft-office'
cask 'near-lock'
cask 'ngrok'
cask 'postman'
cask 'psequel'
cask 'sequel-pro'
cask 'shiftit'
cask 'skype'
cask 'soundflower'
cask 'spotify'
cask 'sublime-text-dev'
cask 'synergy'
cask 'the-unarchiver'
cask 'totalspaces'
cask 'touchswitcher'
cask 'tunnelblick'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
mas 'NetSpot Wi-Fi Reporter', id: 678464954
mas 'NetSpot', id: 514951692
mas 'Quiver', id: 866773894
mas 'WinArchiver Lite', id: 414855915
mas '050plus', id: 694926804
mas 'FreeMan', id: 510934532
mas 'Keynote', id: 409183694
mas 'Mousepose', id: 405904955
mas 'LINE', id: 539883307
mas 'MARKETSPEED', id: 946680495
mas 'Network Radar', id: 507659816
mas 'ToyViewer', id: 414298354
mas 'WiFi Explorer', id: 494803304
mas 'Kobito', id: 896624060
mas 'WiFi Signal', id: 525912054
mas 'Tweetbot', id: 557168941
mas 'Witch', id: 412485838
mas 'Slack', id: 803453959
mas 'Duplicate Photos Fixer Pro', id: 963642514
mas 'PopClip', id: 445189367
mas 'Mactracker', id: 430255202
